name: gitstream

on:
  pull_request:

jobs:
  gitstream:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: linear-b/gitstream-github-action@v2
        with:
          full_repository: ${{ github.repository }}
          head_ref: ${{ github.head_ref }}
          base_ref: ${{ github.base_ref }}
          resolver_url: https://resolver.gitstream.cm
          resolver_token: ${{ secrets.GITSTREAM_TOKEN }}
