name: gitstream

on:
  pull_request:

jobs:
  gitstream:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: linear-b/gitstream-github-action@v2
        with:
          resolver_token: ${{ secrets.GITSTREAM_TOKEN }}
